//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Lan_Line_No { get; set; }
        public string Mobile_No { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string EmailAddress { get; set; }
        public string WhatsAppNo { get; set; }
        public string LogoUrl { get; set; }
    }
}
