//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeMaster
    {
        public CodeMaster()
        {
            this.ReturnDamagedStocks = new HashSet<ReturnDamagedStock>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ReturnDamagedStock> ReturnDamagedStocks { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
    }
}
