//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Sales = new HashSet<Sale>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<int> LanNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public int CreditDays { get; set; }
        public bool IsExistingCustomer { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
