//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuringUnit
    {
        public MeasuringUnit()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string unit { get; set; }
        public decimal MeasureQty { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
