//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PriceDetails = new HashSet<PriceDetail>();
            this.SaleDetails = new HashSet<SaleDetail>();
            this.ReturnDamagedStocks = new HashSet<ReturnDamagedStock>();
            this.Stocks = new HashSet<Stock>();
            this.PurchaseFreeDetails = new HashSet<PurchaseFreeDetail>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> UnitOfMeasure { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int CompanyId { get; set; }
        public decimal ReorderPoint { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual MeasuringUnit MeasuringUnit { get; set; }
        public virtual ICollection<PriceDetail> PriceDetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        public virtual ICollection<ReturnDamagedStock> ReturnDamagedStocks { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<PurchaseFreeDetail> PurchaseFreeDetails { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
    }
}
