//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseFreeDetails = new HashSet<PurchaseFreeDetail>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchasePaymentDetails = new HashSet<PurchasePaymentDetail>();
            this.PurchaseChequePaymentDetails = new HashSet<PurchaseChequePaymentDetail>();
        }
    
        public int BillId { get; set; }
        public Nullable<int> RunningBillNo { get; set; }
        public int CompanyId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> TransportCharges { get; set; }
        public Nullable<decimal> CoolieCharges { get; set; }
        public Nullable<decimal> KCoolieCharges { get; set; }
        public Nullable<decimal> LocalCoolieCharges { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseFreeDetail> PurchaseFreeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasePaymentDetail> PurchasePaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseChequePaymentDetail> PurchaseChequePaymentDetails { get; set; }
    }
}
