//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDamagedStock
    {
        public int Id { get; set; }
        public Nullable<int> BillId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public int PriceId { get; set; }
        public string comments { get; set; }
        public bool isReturn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
