//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDailyTransaction
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> SalesQty { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
