//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public int Id { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> AdjustedQty { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> StockTransId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual StockTransaction StockTransaction { get; set; }
    }
}
